# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Dylan Goldblattz'
tagline:          'A Daybook'
description:      'Technologist & Germanist'
url:              http://www.ndgold.com
baseurl:          /

author:
  name:           'Dylan Goldblatt'
  url:            https://twitter.com/ndgold

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ngoldbla
